@include('layouts.header')
<style>
    :root{
    --fonts:'Poppins', sans-serif;
    --base-color:#ebb700;
    --secondary-color:#1d1d1d;
    --nav-color:#dadada;
    }
    .how-mem{
        color:var(--base-color);
    }
</style>
<div class="user-welcome container-fluid">
        <div class="container">
            <div class="row py-5 d-flex-column align-items-center justify-content-center flex-column complusory-header-inner-page">
                <h1>Terms & Conditions</h1>
            </div>
        </div>
</div>

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <p class="mt-5">
            Membership contract with the Shopping Center and Group International jimta (since March 27, 2021)<br><br>
            Membership agreement with the shopping center and Group International Jimta (since March 27, 2021) This agreement is the contract concluded between you and the Group International Jimta and for this purpose it has the legal value of the contract. Please read it carefully and familiarize yourself with the terms and conditions below; please promise to strictly abide by the terms of this agreement. Once you have accepted and created an account to become members and customers of Jimta Group International, you automatically agree to the following terms and conditions:<br><br>
            1. ACCEPTANCE OF TERMS 1.1 The following terms and conditions of this contract apply to the agreement between Jimta Group International members, customers and the Jimta.org platform; if you use the services of the Jimta.org platform, this indicates that you accept the terms and conditions below. If you do not agree to all of the terms and conditions or have any questions about the agreement, you should consult us. By completing the registration process and clicking on the "I accept" button, you agree to be bound by this agreement, which takes effect immediately.<br><br>
            1.2 Of this agreement, including any text already published by Jimta Group International or which may be published in the future. All the rules forming an integral part of this agreement, and the agreement itself, have the same legal value. In addition to the separate statement, any service of the Jimta.org platform and related services provided by it will be bound by this agreement.<br><br>
            1.3 The terms and conditions of this agreement do not have a termination date, as long as you use the services of the Jimta.org platform, this agreement will have a constraint and restrictions on you, and will always remain valid. Then, you cannot question the validity of this agreement, or request its cancellation because of not having read its contents or because your questions have remained unanswered.<br><br>
            1.4 Jimta has the right to change, upgrade, modify, limit or suspend any Service or its related features, please follow announcements on the Platform or on Jimta Group International's official social media pages, without prior notice. Jimta Group International shall have the absolute right to introduce new features, plates, applications or other services. All new features, functions, applications, terms, modifications, updates and changes are covered in this agreement unless otherwise stated.<br><br>
            1.5 Jimta Group International has set forth all agreements, terms and utility of treaties or other legal documents which shall be deemed fit and governed by law. 2. MEMBER AND CUSTOMER REGISTRATIONS<br><br>
            2.1 All users, members and customers must be at least 18 years old, have the legal capacity of the corresponding rights and capacity of natural persons, legal persons or other organizations, independently bear legal responsibility. When you complete the registration process or pass the consent of the other method of the Jimta.net platform in the actual use of this platform, namely that you confirm that you have the qualification of a legal subject, you can independently assume legal responsibility. All liability will be your responsibility and that of your legal guardian if required, if you have no legal qualifications and you cause losses.<br><br>
            2.2 All users must be absolutely honest when registering on the platform, the user agrees to provide 100% correctly registered information, accurate, complete, legal and effective, and any modification of user registration information , must be updated in a timely manner in their account on the platform. If the user voluntarily provides erroneous, inaccurate, non-exhaustive information, these must therefore bear, absorb the responsibility and the corresponding consequences and Jimta Group International reserves the right to terminate the account of the dishonest user, and prohibit him to use the services of this platform again.<br><br>
            2.3 When you successfully register, you become a member and customer of the Jimta.org platform, at the end of the transaction, you will get your usernames and passwords and other account information, you can change your password password in accordance with the rules and regulations of this site and company instructions.<br><br>
            2.4 Your Membership Information shall not constitute a violation or alleged violation of the rights and legitimate interests of others. Otherwise, Jimta Group International shall have the right to terminate your online stores with the Jimta.org platform service, cancel your account, suspend it and even terminate it.<br><br>
            2.5 You must be careful with your online store accounts, with reasonable storage, you must use your provided username and password, and behave reasonably at all times. Unless a law or a judicial decision, or then an express permission of Jimta Group International, otherwise, the name of the member, his identifiers of connection and transaction, his passwords cannot in any way be transferred, given as a gift or as an inheritance (with the exception of property rights linked to the account).<br><br>
            3. THE SERVICES 3.3.1 The services offered are free and without expiry date unless terminated in accordance with the provisions of this agreement.<br><br>
            3.2 Members from certain countries or regions may be offered exclusive promotions different from other regions. There are no warranties or representations where the feature, or any specific feature, is applicable to all members on the Jimta.org platform.<br><br>
            3.3 The user on this site to browse, order the activities such as shopping, print sharing, implies the user's real name / contact name, address, telephone, e-mail and other private information, this site will remain strictly confidential. Unless it first obtains permission from users or is otherwise required by law, this site will not disclose information about users' private lives to the outside world.<br><br>
            3.4 If you notice any illegal use that may endanger the security of your account, you must immediately inform us as soon as possible so that Jimta Group International suspends the services concerned and reports it to the public security organ. Please understand that Jimta Group International requires action on your claim within a reasonable time, Jimta Group International will not take any responsibility, before taking any action (including but not limited to any loss)<br><br>
            3.5 Any sums started in the subscription of any pack or product are not refundable on personal cancellation of the subscriber.<br><br>
            3.6 Any subscription commitment for the acquisition of land must be settled within a maximum of 12 months (1 year) from the first payment; after this period the company reserves the right to offer you another site according to its distribution scheme after the balance of your commitment.<br><br>
            4. AUTHORIZATION 4.1 In order to allow you to use the Jimta.org platform, services of associated companies and other organizations (hereinafter referred to as "other services"), you agree and authorize Jimta Group International to put you in the registration process, to allow you to use the Jimta.org platform and the services provided, training, information, to provide you with other services associated companies of Jimta Group International or other organizations, or to make available to you upon registration, use of other services, training and information from other services associated companies of Jimta or other organizations.<br><br>
            4.2 You grant Jimta Group International the right to reasonable use of User Information.<br><br>
            4.3 You agree that Jimta may send via email, text messaging, telephone and other forms to register on this site, the user initiating the transaction, the recipient to facilitate the sending of order information or further promotion.<br><br>
            4.4 You understand and agree that Jimta Group International has the right to meet the requirements of the national judicial, administrative and other departments, to provide you with the Jimta platform to fill in registration information and transaction records and other necessary information. If you are suspected of infringing the intellectual property rights of others, Jimta Group shall have the right to prior judgment of the presence of an infringement suspect, provide your identity information to the holder.<br><br>
            4.5 Users agree that jimta can log in to enter the registered account user through the user registration information, information such as username, password, for evidence preservation, including including but not limited to notarization, witness, etc.<br><br>
            5. STANDARD OF USE Use of registration to Jimta.net platform services: Members and customers may disclose their purchase transactions, request additional information about services and products, an intention to agree to buying and selling, to evaluate the other party, to participate in activities, for impression sharing and the use of the information service and other technical services. However, by using the Jimta processes and service, you must agree to strictly comply with the following obligations:<br><br>
            5.1 You may not post, transfer or damage state laws and regulations, social information and information involving national security or public interests;<br><br>
            5.2 Not to use this site to engage in trade secrets, steal personal information and other illegal and criminal activities;<br><br>
            5.3 Do not engage in any inappropriate actions or behaviors that may disrupt the normal order of online transactions.<br><br>
            5.4 Do not facilitate any violation of copyright, trademark and other intellectual property rights or other legitimate content rights.<br><br>
            5.5 Not to evaluate other members in an imagined or false way, not to deceive other members and customers, not to disclose content information that is defamed, threatened or harassed.<br><br>
            5.6 Do not distribute content containing pornography that may be harmful to minors.<br><br>
            5.7 Do not post discrimination on the basis of race, gender, religion, nationality, disability, sexual orientation or information age.<br><br>
            5.8 Do not upload, post or share anything that could destroy or limit the function of any computer software, hardware or telecommunications equipment viruses or any other computer code, files or programs.<br><br>
            5.9 Do not use the jimta Mall platform on data for commercial purposes, including but not limited to in any way such as copying, distributing data with the jimta.org platform, without the prior written consent of Jimta Group International. Do not use any device, software or program to interfere with the normal operation of the Jimta.org platform<br><br>
            5.10 This site has the right to remove a station that does not comply with the legal policy or promotes false information content without informing the user.<br><br>
            5.11 If you fail to comply with the above provisions, you agree that the site and Jimta Group International have the right to make independent judgment and suspend, terminate or close the user account, orders and other measures.
            5.12 In the event of a dispute, Jimta Group International has the right on the platform of the disputing parties and the measures taken by Jimta including access to legal and legal documents, as well as effective administrative and judicial bodies to confirm whether any violation of the provisions of this agreement and/or the rules or alleged violation of the provisions of the laws and regulations has been committed according to their own judgment.<br><br>
            5.13 If you have disclosed on the Jimta.org platform an alleged illegal or suspected violation of other legal rights or a breach of this Agreement and/or the Information Rules, Jimta shall have the right to have you removed without further notice, and in accordance with the provisions of the rules is punished.<br><br>
            5.14 In the event of any act or behavior by you which may impact the Jimta.org Platform, Jimta Group International reserves the right to unilaterally decide whether your behavior and actions constitute a breach of this Agreement and/or Rules , and suspend or close the user account and other measures.<br><br>
            5.15 In the event of an alleged violation or actions harmful to a third party, you will bear full legal responsibility, and will ensure that Jimta Group International is not affected in any way under penalty of seeing your costs increase.<br><br>
            5.16 If you are suspected of having violated the law or the provisions of this agreement mentioned above, and you cause Jimta to suffer a loss, a claim from a third party, or a sanction by an administrative department, you shall indemnify jimta Group International for losses and/or expenses incurred, including reasonable attorneys' fees.<br><br>
            5.17 If you continue to threaten without proof, of your own recklessness, to bring the company to justice, such as the police, higher courts, tax authorities, etc. and cause Jimta to suffer losses from third parties, the company will not hesitate to suspend, terminate and cancel all your usernames and account IDs on the Jimta.org platforms without notice. Jimta Group International reserves the right to terminate users who use any Jimta services.<br><br>
            6. TRANSACTIONS BETWEEN BUYERS AND SUPPLIERS 6.1 For all transactions carried out on this platform, please carefully confirm the name of the products purchased, the price, the quantity, the type, the specifications, the size, etc. When placing an order, please indicate what you want to buy, quantity, price and payment method, buyer's full contact details, delivery address, etc. If the registration information you provide is inaccurate or incomplete, then users must bear the corresponding responsibility and consequences, and Jimta reserves the right to terminate the accounts of said users from the Jimta.org platform.<br><br>
            6.2 The system generates order information based on the data you fill in when you initiate the transaction. The content of the automatically generated data is the only contract you sent to merchants; The merchant after having received your order information, initiates the shipment of the purchased products from the warehouse (marked by a good exit of the goods), this completes the establishment of the contract between you and the merchant; If an order includes several varieties of products and the merchant only sends you part of the products, this partial transaction will also be sufficient to establish the purchase and sale contract between the seller and yourself.<br><br>
            6.3 You fully understand and agree that if you purchase Goods, the Merchant has the right to cancel the order if out of stock. This platform has no guarantee when you submit the order that the products will be available.<br><br>
            6.4 Jimta Group International partner companies or traders will send the goods to your specified delivery address or ask you to collect them from the respective service center offices etc. You therefore understand that the fast delivery times mentioned on this platform are for reference, the actual delivery time may therefore be slightly different. The platform for managers, owners or its associates will therefore not be liable for not being able to deliver or delay a delivery; this responsibility rests with the merchants. If an order cannot be delivered, Jimta will store it for 30 days. If said orders are still unclaimed after 30 days, Jimta has the right to dispose of them. If your delivery is delayed due to force majeure or any other justified reason, the company will understand this and the products will be delivered to you at the appropriate time.<br><br>
            7. LIMITATION OF LIABILITY 7.1 This platform as you know, like other virtual spaces for consultation, negotiation and exchanges, due to the virtual nature of the Internet, makes it difficult to validate user information. due to the very nature of the Internet. Unless expressly instructed in writing, this platform does not store the information posted on the platform, content, materials, products and services and all obligations in the commercial performance of the ability to make any form of warranty, except contrary provision of laws and regulations. So, to prompt you here: You must be careful in judging to determine the authenticity, legitimacy and effectiveness of the goods and/or relevant information.<br><br>
            7.2 Where Jimta Group International, through receipt of your complaints, notices or through competent authority in accordance with laws and regulations, has reason to believe that a particular member or a specific transaction may be illegal, Jimta may take the corresponding measures in accordance with the contract or in accordance with the law.<br><br>
            7.3 You understand and agree that Jimta Group International cannot be held liable for compensation for any damage caused by the following situations, the list of which is not exhaustive; profits, goodwill, use, loss of data or any other loss or damage. For any loss or damage (including direct, indirect, special or consequential loss or damage, such as loss of income or profit, damage to computer system or loss of data) caused by you or the use by any person for information contained in or linked to this website, liability (including, but not limited to, liability for negligence) is the responsibility of the user for any reason whatsoever.<br><br>
            7.3.1 Use of your account by third parties or modification of your data without our consent.<br><br>
            7.3.2 Your lack of knowledge of the services offered by the Jimta.org platform. All users involved in trading on the platform should understand that the rewards generated in the wholesale and retail process are entirely determined by the market, and the company is only responsible for the safekeeping and recording of products involved. The company's platform is a platform for members to buy and sell freely. Purchases and deposits executed on the platform are personal acts of good faith towards the company. The company only oversees and manages the real estate and training component platform. Any disputes arising therefrom will be resolved by Customers and Members privately and the Company will not handle any disputes on behalf of Members. Your misinterpretation of this agreement is your own responsibility and Jimta Group International cannot be held responsible for it. This statement is hereby sent in this regard, of vital importance to all members and customers of Jimta Group International.<br><br>
            7.3.3 Any other loss or damage associated with a jimta.org platform service, rather than due to Jimta Group International as an entity. Users' use of this website means that the user accepts responsibility for all risks associated with browsing this Jimta.org website. The company can not be held responsible for any direct, relevant, consequential, indirect or monetary damage caused by the transactions of a user or because of his use of the data contained on the site Jimta.org<br><br>
            7.4 Jimta Group International is not responsible, due to force majeure legal provisions, for normal maintenance of information network equipment, information network connection failures, computer, communications or other system failures, power outages, labor disputes, if productivity and production data are insufficient , the administrative and judicial bodies related to an order or a third party causes of this platform can not control this platform can not serve or delay, loss of data information, records, but jimta will help deal with related issues.<br><br>
            8. PROPRIETARY RIGHTS 8.1 Jimta Group International is the sole owner of all legal rights or licenses to provide Services. The Service reflects trade secrets and worldwide copyright and intellectual property rights protected by law. These include all services, title and intellectual property provided by Jimta or its affiliates. Under this Agreement Jimta Group International reserves final rights.<br><br>
            8.2 Jimta.org and the related set of ICONS as well as the trademark belong to Jimta GROUP International and fall under the protection of copyright, trademark and other rights exclusive to the protection of the law. Unauthorized reproduction, modification, use or publication of the trademark symbols, names or icons is strictly prohibited. 8.3 Of this agreement applicable to the laws<br><br>

            </p>
        </div>
    </div>
</div>
@include('layouts.footer')